/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_ROBOTSYSTEMCOMMUNICATION_PROTO_ROBOTSYSTEMCOMMUNICATION_PB_H_INCLUDED
#define PB_ROBOTSYSTEMCOMMUNICATION_PROTO_ROBOTSYSTEMCOMMUNICATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _robotsystemcommunication_StatusType {
    robotsystemcommunication_StatusType_UNKNOWN = 0,
    robotsystemcommunication_StatusType_OK = 1,
    robotsystemcommunication_StatusType_ERROR = 2
} robotsystemcommunication_StatusType;

typedef enum _robotsystemcommunication_ImageType {
    robotsystemcommunication_ImageType_JPG = 0,
    robotsystemcommunication_ImageType_PNG = 1
} robotsystemcommunication_ImageType;

/* Struct definitions */
typedef struct _robotsystemcommunication_BrainActionRequest {
    pb_callback_t lowerObservations;
    pb_callback_t upperObservations;
} robotsystemcommunication_BrainActionRequest;

typedef struct _robotsystemcommunication_RobotPingRequest {
    char dummy_field;
} robotsystemcommunication_RobotPingRequest;

typedef struct _robotsystemcommunication_SimulationScreenCaptureResponse {
    pb_callback_t image;
} robotsystemcommunication_SimulationScreenCaptureResponse;

typedef struct _robotsystemcommunication_BrainActionResponse {
    int32_t action;
    int32_t leftMotorAction;
    int32_t rightMotorAction;
    int32_t actionTimeout;
} robotsystemcommunication_BrainActionResponse;

typedef struct _robotsystemcommunication_RobotActionRequest {
    int32_t leftMotorAction;
    int32_t rightMotorAction;
    int32_t actionTimeout;
} robotsystemcommunication_RobotActionRequest;

typedef struct _robotsystemcommunication_RobotActionResponse {
    robotsystemcommunication_StatusType status;
} robotsystemcommunication_RobotActionResponse;

typedef struct _robotsystemcommunication_RobotPingResponse {
    char ipAddress[32];
    char macAddress[32];
    pb_callback_t robotId;
    pb_callback_t teamId;
    float voltage;
    float startupVoltage;
} robotsystemcommunication_RobotPingResponse;

typedef struct _robotsystemcommunication_SimulationActionRequest {
    int32_t action;
    int32_t leftMotorAction;
    int32_t rightMotorAction;
    int32_t actionTimeout;
} robotsystemcommunication_SimulationActionRequest;

typedef struct _robotsystemcommunication_SimulationActionResponse {
    robotsystemcommunication_StatusType status;
} robotsystemcommunication_SimulationActionResponse;

typedef struct _robotsystemcommunication_SimulationScreenCaptureRequest {
    int32_t height;
    int32_t width;
    robotsystemcommunication_ImageType imageType;
    int32_t jpgQuality;
} robotsystemcommunication_SimulationScreenCaptureRequest;

typedef struct _robotsystemcommunication_RobotRequest {
    uint32_t reqId;
    pb_size_t which_req;
    union {
        robotsystemcommunication_RobotActionRequest act;
        robotsystemcommunication_RobotPingRequest ping;
    } req;
} robotsystemcommunication_RobotRequest;

typedef struct _robotsystemcommunication_RobotResponse {
    uint32_t reqId;
    pb_size_t which_resp;
    union {
        robotsystemcommunication_RobotActionResponse act;
        robotsystemcommunication_RobotPingResponse ping;
    } resp;
} robotsystemcommunication_RobotResponse;


/* Helper constants for enums */
#define _robotsystemcommunication_StatusType_MIN robotsystemcommunication_StatusType_UNKNOWN
#define _robotsystemcommunication_StatusType_MAX robotsystemcommunication_StatusType_ERROR
#define _robotsystemcommunication_StatusType_ARRAYSIZE ((robotsystemcommunication_StatusType)(robotsystemcommunication_StatusType_ERROR+1))

#define _robotsystemcommunication_ImageType_MIN robotsystemcommunication_ImageType_JPG
#define _robotsystemcommunication_ImageType_MAX robotsystemcommunication_ImageType_PNG
#define _robotsystemcommunication_ImageType_ARRAYSIZE ((robotsystemcommunication_ImageType)(robotsystemcommunication_ImageType_PNG+1))


/* Initializer values for message structs */
#define robotsystemcommunication_RobotActionRequest_init_default {0, 0, 0}
#define robotsystemcommunication_RobotActionResponse_init_default {_robotsystemcommunication_StatusType_MIN}
#define robotsystemcommunication_RobotPingRequest_init_default {0}
#define robotsystemcommunication_RobotPingResponse_init_default {"", "", {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define robotsystemcommunication_RobotRequest_init_default {0, 0, {robotsystemcommunication_RobotActionRequest_init_default}}
#define robotsystemcommunication_RobotResponse_init_default {0, 0, {robotsystemcommunication_RobotActionResponse_init_default}}
#define robotsystemcommunication_BrainActionResponse_init_default {0, 0, 0, 0}
#define robotsystemcommunication_BrainActionRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define robotsystemcommunication_SimulationScreenCaptureResponse_init_default {{{NULL}, NULL}}
#define robotsystemcommunication_SimulationScreenCaptureRequest_init_default {0, 0, _robotsystemcommunication_ImageType_MIN, 0}
#define robotsystemcommunication_SimulationActionRequest_init_default {0, 0, 0, 0}
#define robotsystemcommunication_SimulationActionResponse_init_default {_robotsystemcommunication_StatusType_MIN}
#define robotsystemcommunication_RobotActionRequest_init_zero {0, 0, 0}
#define robotsystemcommunication_RobotActionResponse_init_zero {_robotsystemcommunication_StatusType_MIN}
#define robotsystemcommunication_RobotPingRequest_init_zero {0}
#define robotsystemcommunication_RobotPingResponse_init_zero {"", "", {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define robotsystemcommunication_RobotRequest_init_zero {0, 0, {robotsystemcommunication_RobotActionRequest_init_zero}}
#define robotsystemcommunication_RobotResponse_init_zero {0, 0, {robotsystemcommunication_RobotActionResponse_init_zero}}
#define robotsystemcommunication_BrainActionResponse_init_zero {0, 0, 0, 0}
#define robotsystemcommunication_BrainActionRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define robotsystemcommunication_SimulationScreenCaptureResponse_init_zero {{{NULL}, NULL}}
#define robotsystemcommunication_SimulationScreenCaptureRequest_init_zero {0, 0, _robotsystemcommunication_ImageType_MIN, 0}
#define robotsystemcommunication_SimulationActionRequest_init_zero {0, 0, 0, 0}
#define robotsystemcommunication_SimulationActionResponse_init_zero {_robotsystemcommunication_StatusType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define robotsystemcommunication_BrainActionRequest_lowerObservations_tag 1
#define robotsystemcommunication_BrainActionRequest_upperObservations_tag 2
#define robotsystemcommunication_SimulationScreenCaptureResponse_image_tag 1
#define robotsystemcommunication_BrainActionResponse_action_tag 1
#define robotsystemcommunication_BrainActionResponse_leftMotorAction_tag 2
#define robotsystemcommunication_BrainActionResponse_rightMotorAction_tag 3
#define robotsystemcommunication_BrainActionResponse_actionTimeout_tag 4
#define robotsystemcommunication_RobotActionRequest_leftMotorAction_tag 1
#define robotsystemcommunication_RobotActionRequest_rightMotorAction_tag 2
#define robotsystemcommunication_RobotActionRequest_actionTimeout_tag 3
#define robotsystemcommunication_RobotActionResponse_status_tag 1
#define robotsystemcommunication_RobotPingResponse_ipAddress_tag 1
#define robotsystemcommunication_RobotPingResponse_macAddress_tag 2
#define robotsystemcommunication_RobotPingResponse_robotId_tag 3
#define robotsystemcommunication_RobotPingResponse_teamId_tag 4
#define robotsystemcommunication_RobotPingResponse_voltage_tag 5
#define robotsystemcommunication_RobotPingResponse_startupVoltage_tag 6
#define robotsystemcommunication_SimulationActionRequest_action_tag 1
#define robotsystemcommunication_SimulationActionRequest_leftMotorAction_tag 2
#define robotsystemcommunication_SimulationActionRequest_rightMotorAction_tag 3
#define robotsystemcommunication_SimulationActionRequest_actionTimeout_tag 4
#define robotsystemcommunication_SimulationActionResponse_status_tag 1
#define robotsystemcommunication_SimulationScreenCaptureRequest_height_tag 1
#define robotsystemcommunication_SimulationScreenCaptureRequest_width_tag 2
#define robotsystemcommunication_SimulationScreenCaptureRequest_imageType_tag 3
#define robotsystemcommunication_SimulationScreenCaptureRequest_jpgQuality_tag 4
#define robotsystemcommunication_RobotRequest_act_tag 10
#define robotsystemcommunication_RobotRequest_ping_tag 11
#define robotsystemcommunication_RobotRequest_reqId_tag 1
#define robotsystemcommunication_RobotResponse_act_tag 10
#define robotsystemcommunication_RobotResponse_ping_tag 11
#define robotsystemcommunication_RobotResponse_reqId_tag 1

/* Struct field encoding specification for nanopb */
#define robotsystemcommunication_RobotActionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    leftMotorAction,   1) \
X(a, STATIC,   SINGULAR, INT32,    rightMotorAction,   2) \
X(a, STATIC,   SINGULAR, INT32,    actionTimeout,     3)
#define robotsystemcommunication_RobotActionRequest_CALLBACK NULL
#define robotsystemcommunication_RobotActionRequest_DEFAULT NULL

#define robotsystemcommunication_RobotActionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define robotsystemcommunication_RobotActionResponse_CALLBACK NULL
#define robotsystemcommunication_RobotActionResponse_DEFAULT NULL

#define robotsystemcommunication_RobotPingRequest_FIELDLIST(X, a) \

#define robotsystemcommunication_RobotPingRequest_CALLBACK NULL
#define robotsystemcommunication_RobotPingRequest_DEFAULT NULL

#define robotsystemcommunication_RobotPingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ipAddress,         1) \
X(a, STATIC,   SINGULAR, STRING,   macAddress,        2) \
X(a, CALLBACK, SINGULAR, STRING,   robotId,           3) \
X(a, CALLBACK, SINGULAR, STRING,   teamId,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    startupVoltage,    6)
#define robotsystemcommunication_RobotPingResponse_CALLBACK pb_default_field_callback
#define robotsystemcommunication_RobotPingResponse_DEFAULT NULL

#define robotsystemcommunication_RobotRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reqId,             1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (req,act,req.act),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (req,ping,req.ping),  11)
#define robotsystemcommunication_RobotRequest_CALLBACK NULL
#define robotsystemcommunication_RobotRequest_DEFAULT NULL
#define robotsystemcommunication_RobotRequest_req_act_MSGTYPE robotsystemcommunication_RobotActionRequest
#define robotsystemcommunication_RobotRequest_req_ping_MSGTYPE robotsystemcommunication_RobotPingRequest

#define robotsystemcommunication_RobotResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reqId,             1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (resp,act,resp.act),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (resp,ping,resp.ping),  11)
#define robotsystemcommunication_RobotResponse_CALLBACK NULL
#define robotsystemcommunication_RobotResponse_DEFAULT NULL
#define robotsystemcommunication_RobotResponse_resp_act_MSGTYPE robotsystemcommunication_RobotActionResponse
#define robotsystemcommunication_RobotResponse_resp_ping_MSGTYPE robotsystemcommunication_RobotPingResponse

#define robotsystemcommunication_BrainActionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    action,            1) \
X(a, STATIC,   SINGULAR, INT32,    leftMotorAction,   2) \
X(a, STATIC,   SINGULAR, INT32,    rightMotorAction,   3) \
X(a, STATIC,   SINGULAR, INT32,    actionTimeout,     4)
#define robotsystemcommunication_BrainActionResponse_CALLBACK NULL
#define robotsystemcommunication_BrainActionResponse_DEFAULT NULL

#define robotsystemcommunication_BrainActionRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    lowerObservations,   1) \
X(a, CALLBACK, REPEATED, FLOAT,    upperObservations,   2)
#define robotsystemcommunication_BrainActionRequest_CALLBACK pb_default_field_callback
#define robotsystemcommunication_BrainActionRequest_DEFAULT NULL

#define robotsystemcommunication_SimulationScreenCaptureResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    image,             1)
#define robotsystemcommunication_SimulationScreenCaptureResponse_CALLBACK pb_default_field_callback
#define robotsystemcommunication_SimulationScreenCaptureResponse_DEFAULT NULL

#define robotsystemcommunication_SimulationScreenCaptureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    height,            1) \
X(a, STATIC,   SINGULAR, INT32,    width,             2) \
X(a, STATIC,   SINGULAR, UENUM,    imageType,         3) \
X(a, STATIC,   SINGULAR, INT32,    jpgQuality,        4)
#define robotsystemcommunication_SimulationScreenCaptureRequest_CALLBACK NULL
#define robotsystemcommunication_SimulationScreenCaptureRequest_DEFAULT NULL

#define robotsystemcommunication_SimulationActionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    action,            1) \
X(a, STATIC,   SINGULAR, INT32,    leftMotorAction,   2) \
X(a, STATIC,   SINGULAR, INT32,    rightMotorAction,   3) \
X(a, STATIC,   SINGULAR, INT32,    actionTimeout,     4)
#define robotsystemcommunication_SimulationActionRequest_CALLBACK NULL
#define robotsystemcommunication_SimulationActionRequest_DEFAULT NULL

#define robotsystemcommunication_SimulationActionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define robotsystemcommunication_SimulationActionResponse_CALLBACK NULL
#define robotsystemcommunication_SimulationActionResponse_DEFAULT NULL

extern const pb_msgdesc_t robotsystemcommunication_RobotActionRequest_msg;
extern const pb_msgdesc_t robotsystemcommunication_RobotActionResponse_msg;
extern const pb_msgdesc_t robotsystemcommunication_RobotPingRequest_msg;
extern const pb_msgdesc_t robotsystemcommunication_RobotPingResponse_msg;
extern const pb_msgdesc_t robotsystemcommunication_RobotRequest_msg;
extern const pb_msgdesc_t robotsystemcommunication_RobotResponse_msg;
extern const pb_msgdesc_t robotsystemcommunication_BrainActionResponse_msg;
extern const pb_msgdesc_t robotsystemcommunication_BrainActionRequest_msg;
extern const pb_msgdesc_t robotsystemcommunication_SimulationScreenCaptureResponse_msg;
extern const pb_msgdesc_t robotsystemcommunication_SimulationScreenCaptureRequest_msg;
extern const pb_msgdesc_t robotsystemcommunication_SimulationActionRequest_msg;
extern const pb_msgdesc_t robotsystemcommunication_SimulationActionResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define robotsystemcommunication_RobotActionRequest_fields &robotsystemcommunication_RobotActionRequest_msg
#define robotsystemcommunication_RobotActionResponse_fields &robotsystemcommunication_RobotActionResponse_msg
#define robotsystemcommunication_RobotPingRequest_fields &robotsystemcommunication_RobotPingRequest_msg
#define robotsystemcommunication_RobotPingResponse_fields &robotsystemcommunication_RobotPingResponse_msg
#define robotsystemcommunication_RobotRequest_fields &robotsystemcommunication_RobotRequest_msg
#define robotsystemcommunication_RobotResponse_fields &robotsystemcommunication_RobotResponse_msg
#define robotsystemcommunication_BrainActionResponse_fields &robotsystemcommunication_BrainActionResponse_msg
#define robotsystemcommunication_BrainActionRequest_fields &robotsystemcommunication_BrainActionRequest_msg
#define robotsystemcommunication_SimulationScreenCaptureResponse_fields &robotsystemcommunication_SimulationScreenCaptureResponse_msg
#define robotsystemcommunication_SimulationScreenCaptureRequest_fields &robotsystemcommunication_SimulationScreenCaptureRequest_msg
#define robotsystemcommunication_SimulationActionRequest_fields &robotsystemcommunication_SimulationActionRequest_msg
#define robotsystemcommunication_SimulationActionResponse_fields &robotsystemcommunication_SimulationActionResponse_msg

/* Maximum encoded size of messages (where known) */
#define robotsystemcommunication_RobotActionRequest_size 33
#define robotsystemcommunication_RobotActionResponse_size 2
#define robotsystemcommunication_RobotPingRequest_size 0
/* robotsystemcommunication_RobotPingResponse_size depends on runtime parameters */
#define robotsystemcommunication_RobotRequest_size 41
/* robotsystemcommunication_RobotResponse_size depends on runtime parameters */
#define robotsystemcommunication_BrainActionResponse_size 44
/* robotsystemcommunication_BrainActionRequest_size depends on runtime parameters */
/* robotsystemcommunication_SimulationScreenCaptureResponse_size depends on runtime parameters */
#define robotsystemcommunication_SimulationScreenCaptureRequest_size 35
#define robotsystemcommunication_SimulationActionRequest_size 44
#define robotsystemcommunication_SimulationActionResponse_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
