/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "RobotSystemCommunication.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(robotsystemcommunication_RobotActionRequest, robotsystemcommunication_RobotActionRequest, AUTO)


PB_BIND(robotsystemcommunication_RobotActionResponse, robotsystemcommunication_RobotActionResponse, AUTO)


PB_BIND(robotsystemcommunication_RobotPingRequest, robotsystemcommunication_RobotPingRequest, AUTO)


PB_BIND(robotsystemcommunication_RobotPingResponse, robotsystemcommunication_RobotPingResponse, AUTO)


PB_BIND(robotsystemcommunication_BrainActionResponse, robotsystemcommunication_BrainActionResponse, AUTO)


PB_BIND(robotsystemcommunication_BrainActionRequest, robotsystemcommunication_BrainActionRequest, AUTO)


PB_BIND(robotsystemcommunication_SimulationScreenCaptureResponse, robotsystemcommunication_SimulationScreenCaptureResponse, AUTO)


PB_BIND(robotsystemcommunication_SimulationScreenCaptureRequest, robotsystemcommunication_SimulationScreenCaptureRequest, AUTO)


PB_BIND(robotsystemcommunication_SimulationActionRequest, robotsystemcommunication_SimulationActionRequest, AUTO)


PB_BIND(robotsystemcommunication_SimulationActionResponse, robotsystemcommunication_SimulationActionResponse, AUTO)





